load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "types",
    srcs = [
        "card.go",
        "cycle.go",
        "trait.go",
    ],
    importpath = "github.com/squk/lotrlcg/cmd/beornextract/types",
    visibility = ["//visibility:public"],
)
